#include "JWModules.hpp"

RACK_PLUGIN_MODEL_DECLARE(JW_Modules, Cat);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, BouncyBalls);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, FullScope);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, GridSeq);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, Quantizer);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, MinMax);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, NoteSeq);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, SimpleClock);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, ThingThing);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, WavHead);
RACK_PLUGIN_MODEL_DECLARE(JW_Modules, XYPad);

RACK_PLUGIN_INIT(JW_Modules) {
   RACK_PLUGIN_INIT_ID();

	RACK_PLUGIN_MODEL_ADD(JW_Modules, Cat);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, BouncyBalls);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, FullScope);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, GridSeq);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, Quantizer);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, MinMax);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, NoteSeq);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, SimpleClock);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, ThingThing);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, WavHead);
	RACK_PLUGIN_MODEL_ADD(JW_Modules, XYPad);
}
