SLUG=Bidoo

include ../../../build_plugin_pre_msvc.mk

EXTRAFLAGS+= -DUSE_KISS_FFT -Idep/include -I./src/dep/audiofile -I./src/dep/filters -I./src/dep/freeverb \
 -I./src/dep/gist/libs/kiss_fft130 -I./src/dep/gist/src -I./src/dep/minimp3\
 -I./src/dep/gist/src/mfcc -I./src/dep/gist/src/core -I./src/dep/gist/src/fft \
 -I./src/dep/gist/src/onset-detection-functions -I./src/dep/gist/src/pitch

include make.objects

include ../../../build_plugin_post_msvc.mk
