#include "SubmarineFree.hpp"

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AG104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AG106);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AO106);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AO112);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AO118);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AO124);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AO136);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BB120);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, EO102);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF110);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF120);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF212);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, LA108);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, LD103);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, LD106);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, NG106);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, NG112);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, OG104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, OG106);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PG104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PG112);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO204);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, SS112);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, SS208);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, SS212);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, SS220);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, SS221);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, TD116);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, TD202);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, TF101);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, TM105);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, WK101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, WK205);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF201);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF202);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XG104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XG106);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP108);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP110);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP112);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP116);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP120);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP124);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP132);

RACK_PLUGIN_INIT(SubmarineFree) {
   RACK_PLUGIN_INIT_ID();
   RACK_PLUGIN_INIT_VERSION("0.6.8");
   RACK_PLUGIN_INIT_WEBSITE("https://github.com/david-c14/SubmarineFree");
   RACK_PLUGIN_INIT_MANUAL("https://github.com/david-c14/SubmarineFree");

	// Add all Models defined throughout the plugin
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, AG104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, AG106);

   RACK_PLUGIN_MODEL_ADD(SubmarineFree, AO106);
   RACK_PLUGIN_MODEL_ADD(SubmarineFree, AO112);
   RACK_PLUGIN_MODEL_ADD(SubmarineFree, AO118);
   RACK_PLUGIN_MODEL_ADD(SubmarineFree, AO124);
   RACK_PLUGIN_MODEL_ADD(SubmarineFree, AO136);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BB120);

   RACK_PLUGIN_MODEL_ADD(SubmarineFree, EO102);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF110);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF120);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF212);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, LA108);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, LD103);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, LD106);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, NG106);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, NG112);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, OG104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, OG106);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PG104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PG112);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO204);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, SS112);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, SS208);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, SS212);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, SS220);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, SS221);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, TD116);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, TD202);

   RACK_PLUGIN_MODEL_ADD(SubmarineFree, TF101);

   RACK_PLUGIN_MODEL_ADD(SubmarineFree, TM105);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, WK101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, WK205);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF201);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF202);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XG104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XG106);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP108);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP110);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP112);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP116);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP120);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP124);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP132);
}
