#include "SubmarineFree.hpp"

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, AG106);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BB120);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF110);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF120);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, FF212);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, LA108);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, LD106);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, NG112);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, OG106);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PG112);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, PO204);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, WK101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, WK205);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF201);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XF202);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, XG106);

RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP101);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP102);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP104);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP108);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP110);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP112);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP116);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP120);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP124);
RACK_PLUGIN_MODEL_DECLARE(SubmarineFree, BP132);

RACK_PLUGIN_INIT(SubmarineFree) {
   RACK_PLUGIN_INIT_ID();

	// Add all Models defined throughout the plugin
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, AG106);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BB120);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF110);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF120);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, FF212);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, LA108);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, LD106);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, NG112);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, OG106);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PG112);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, PO204);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, WK101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, WK205);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF201);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XF202);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, XG106);

	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP101);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP102);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP104);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP108);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP110);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP112);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP116);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP120);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP124);
	RACK_PLUGIN_MODEL_ADD(SubmarineFree, BP132);
}
