#include "ZZC.hpp"

RACK_PLUGIN_MODEL_DECLARE(ZZC, Clock);
RACK_PLUGIN_MODEL_DECLARE(ZZC, Divider);
RACK_PLUGIN_MODEL_DECLARE(ZZC, FN3);
RACK_PLUGIN_MODEL_DECLARE(ZZC, SCVCA);
RACK_PLUGIN_MODEL_DECLARE(ZZC, SH8);
RACK_PLUGIN_MODEL_DECLARE(ZZC, SRC);

RACK_PLUGIN_INIT(ZZC) {
   RACK_PLUGIN_INIT_ID();
   RACK_PLUGIN_INIT_VERSION("0.6.6");
   RACK_PLUGIN_INIT_WEBSITE("https://github.com/zezic/ZZC");

   RACK_PLUGIN_MODEL_ADD(ZZC, Clock);
   RACK_PLUGIN_MODEL_ADD(ZZC, Divider);
   RACK_PLUGIN_MODEL_ADD(ZZC, FN3);
   RACK_PLUGIN_MODEL_ADD(ZZC, SCVCA);
   RACK_PLUGIN_MODEL_ADD(ZZC, SH8);
   RACK_PLUGIN_MODEL_ADD(ZZC, SRC);
}
