# statically linked plugins (note: dynamic linking won't work due to VCV Rack's architecture (global vars!))
EXTRALIBS+= $(call plugin_lib,AS)
EXTRALIBS+= $(call plugin_lib,AudibleInstruments)
EXTRALIBS+= $(call plugin_lib,Befaco)
EXTRALIBS+= $(call plugin_lib,Bogaudio)
EXTRALIBS+= $(call plugin_lib,cf)
EXTRALIBS+= $(call plugin_lib,ErraticInstruments)
EXTRALIBS+= $(call plugin_lib,ESeries)
EXTRALIBS+= $(call plugin_lib,Fundamental)
EXTRALIBS+= $(call plugin_lib,HetrickCV)
EXTRALIBS+= $(call plugin_lib,Koralfx-Modules)
EXTRALIBS+= $(call plugin_lib,LindenbergResearch)
EXTRALIBS+= $(call plugin_lib,Qwelk)
EXTRALIBS+= $(call plugin_lib,SonusModular)
EXTRALIBS+= $(call plugin_lib,SubmarineFree)
EXTRALIBS+= $(call plugin_lib,Template)
EXTRALIBS+= $(call plugin_lib,Valley)
EXTRALIBS+= $(call plugin_lib,VultModules)
