SLUG=Southpole-parasites

include ../../../build_plugin_pre_linux.mk

EXTRAFLAGS+= \
	-DTEST \
	-DPARASITES \
	-I./parasites -Ieurorack/ \
	-Dstmlib=stmlib_parasites

include make.objects

include ../../../build_plugin_post_linux.mk
