#
# Makefile for glew lib + GCC
# 
#

include ../yac/install_linux.mk

TARGET_BASENAME=glew

EXTRAFLAGS= -DGLEW_NO_GLU -DGLEW_BUILD -Iinclude/

EXTRALIBS=

PLAF_OBJ= 

include make.objects

ifeq ($(BUILD_64),y)
LIB_INSTALL_PREFIX=../lib/linux_gcc/x64/
else
LIB_INSTALL_PREFIX=../lib/linux_gcc/x86/
endif

include ../yac/staticlib_linux.mk
