#
# Makefile for glew lib + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
#

include ../yac/install_msvc.mk

TARGET_BASENAME=glew

EXTRAFLAGS= -DGLEW_NO_GLU -DGLEW_BUILD -Iinclude/

EXTRALIBS=
# opengl32.lib gdi32.lib user32.lib kernel32.lib

PLAF_OBJ= 

include make.objects

include ../yac/staticlib_msvc.mk
