#
# Makefile for glew lib + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
#

include ../yac/install_msvc.mk

TARGET_BASENAME=glew

EXTRAFLAGS= -DGLEW_NO_GLU -DGLEW_BUILD -Iinclude/

EXTRALIBS=

PLAF_OBJ= 

include make.objects

ifeq ($(BUILD_64),y)
LIB_INSTALL_PREFIX=../lib/msvc/x64/
else
LIB_INSTALL_PREFIX=../lib/msvc/x86/
endif

include ../yac/staticlib_msvc.mk
