SLUG=Template_shared

include ../../../build_shared_plugin_pre.mk

include make.objects

define BIN_POST_FXN
	cp -f $(SLUG).dll ../../../../vst2_bin/plugins/$(SLUG)/plugin.dll.fx
	cp -f $(SLUG).dll ../../../../vst2_bin/plugins/$(SLUG)/plugin.dll.instr
endef

include ../../../build_shared_plugin_post.mk
