#include "AS.hpp"

using namespace rack_plugin_AS;

RACK_PLUGIN_MODEL_DECLARE(AS, ADSR);
RACK_PLUGIN_MODEL_DECLARE(AS, AtNuVrTr);
RACK_PLUGIN_MODEL_DECLARE(AS, BPMCalc);
RACK_PLUGIN_MODEL_DECLARE(AS, BPMClock);
RACK_PLUGIN_MODEL_DECLARE(AS, BlankPanel4);
RACK_PLUGIN_MODEL_DECLARE(AS, BlankPanel6);
RACK_PLUGIN_MODEL_DECLARE(AS, BlankPanel8);
RACK_PLUGIN_MODEL_DECLARE(AS, BlankPanelSpecial);
RACK_PLUGIN_MODEL_DECLARE(AS, Cv2T);
RACK_PLUGIN_MODEL_DECLARE(AS, ReScale);
RACK_PLUGIN_MODEL_DECLARE(AS, DelayPlusFx);
RACK_PLUGIN_MODEL_DECLARE(AS, DelayPlusStereoFx);
RACK_PLUGIN_MODEL_DECLARE(AS, Flow);
RACK_PLUGIN_MODEL_DECLARE(AS, KillGate);
RACK_PLUGIN_MODEL_DECLARE(AS, LaunchGate);
RACK_PLUGIN_MODEL_DECLARE(AS, Merge2_5);
RACK_PLUGIN_MODEL_DECLARE(AS, Mixer8ch);
RACK_PLUGIN_MODEL_DECLARE(AS, MonoVUmeter);
RACK_PLUGIN_MODEL_DECLARE(AS, Multiple2_5);
RACK_PLUGIN_MODEL_DECLARE(AS, PhaserFx);
RACK_PLUGIN_MODEL_DECLARE(AS, QuadVCA);
RACK_PLUGIN_MODEL_DECLARE(AS, ReverbFx);
RACK_PLUGIN_MODEL_DECLARE(AS, ReverbStereoFx);
RACK_PLUGIN_MODEL_DECLARE(AS, SEQ16);
RACK_PLUGIN_MODEL_DECLARE(AS, SawOsc);
RACK_PLUGIN_MODEL_DECLARE(AS, SignalDelay);
RACK_PLUGIN_MODEL_DECLARE(AS, SineOsc);
RACK_PLUGIN_MODEL_DECLARE(AS, Steps);
RACK_PLUGIN_MODEL_DECLARE(AS, SuperDriveFx);
RACK_PLUGIN_MODEL_DECLARE(AS, TremoloFx);
RACK_PLUGIN_MODEL_DECLARE(AS, TremoloStereoFx);
RACK_PLUGIN_MODEL_DECLARE(AS, TriLFO);
RACK_PLUGIN_MODEL_DECLARE(AS, TriggersMKI);
RACK_PLUGIN_MODEL_DECLARE(AS, TriggersMKII);
RACK_PLUGIN_MODEL_DECLARE(AS, TriggersMKIII);
RACK_PLUGIN_MODEL_DECLARE(AS, VCA);
RACK_PLUGIN_MODEL_DECLARE(AS, WaveShaper);
RACK_PLUGIN_MODEL_DECLARE(AS, StereoVUmeter);

RACK_PLUGIN_INIT(AS) {
   RACK_PLUGIN_INIT_ID();

   RACK_PLUGIN_INIT_WEBSITE("https://github.com/AScustomWorks/AS");
   RACK_PLUGIN_INIT_VERSION("0.6.9");

	//OSCILLATORS
	RACK_PLUGIN_MODEL_ADD(AS, SineOsc);
	RACK_PLUGIN_MODEL_ADD(AS, SawOsc);

	//TOOLS
	RACK_PLUGIN_MODEL_ADD(AS, ADSR);
	RACK_PLUGIN_MODEL_ADD(AS, VCA);
	RACK_PLUGIN_MODEL_ADD(AS, QuadVCA);
	RACK_PLUGIN_MODEL_ADD(AS, TriLFO);
	RACK_PLUGIN_MODEL_ADD(AS, AtNuVrTr);
	
	RACK_PLUGIN_MODEL_ADD(AS, BPMClock);
	RACK_PLUGIN_MODEL_ADD(AS, SEQ16);
	RACK_PLUGIN_MODEL_ADD(AS, Mixer8ch);
	RACK_PLUGIN_MODEL_ADD(AS, MonoVUmeter);
	RACK_PLUGIN_MODEL_ADD(AS, StereoVUmeter);
	RACK_PLUGIN_MODEL_ADD(AS, Steps);
	RACK_PLUGIN_MODEL_ADD(AS, LaunchGate);
	RACK_PLUGIN_MODEL_ADD(AS, KillGate);
	RACK_PLUGIN_MODEL_ADD(AS, Flow);
	RACK_PLUGIN_MODEL_ADD(AS, SignalDelay);
	RACK_PLUGIN_MODEL_ADD(AS, Multiple2_5);
	RACK_PLUGIN_MODEL_ADD(AS, Merge2_5);
	RACK_PLUGIN_MODEL_ADD(AS, TriggersMKI);
	RACK_PLUGIN_MODEL_ADD(AS, TriggersMKII);
	RACK_PLUGIN_MODEL_ADD(AS, TriggersMKIII);
	RACK_PLUGIN_MODEL_ADD(AS, BPMCalc);
	RACK_PLUGIN_MODEL_ADD(AS, Cv2T);
	RACK_PLUGIN_MODEL_ADD(AS, ReScale);

   //EFFECTS	
	RACK_PLUGIN_MODEL_ADD(AS, DelayPlusFx);
	RACK_PLUGIN_MODEL_ADD(AS, DelayPlusStereoFx);
	
	RACK_PLUGIN_MODEL_ADD(AS, PhaserFx);

	RACK_PLUGIN_MODEL_ADD(AS, ReverbFx);
	RACK_PLUGIN_MODEL_ADD(AS, ReverbStereoFx);

	RACK_PLUGIN_MODEL_ADD(AS, SuperDriveFx);

	RACK_PLUGIN_MODEL_ADD(AS, TremoloFx);
	RACK_PLUGIN_MODEL_ADD(AS, TremoloStereoFx);
	
	RACK_PLUGIN_MODEL_ADD(AS, WaveShaper);

	//BLANK PANELS
	RACK_PLUGIN_MODEL_ADD(AS, BlankPanel4);
	RACK_PLUGIN_MODEL_ADD(AS, BlankPanel6);
	RACK_PLUGIN_MODEL_ADD(AS, BlankPanel8);
	RACK_PLUGIN_MODEL_ADD(AS, BlankPanelSpecial);
}
