#include "bsp.hpp"

RACK_PLUGIN_MODEL_DECLARE(bsp, AttenuMixer);
RACK_PLUGIN_MODEL_DECLARE(bsp, Bias);
RACK_PLUGIN_MODEL_DECLARE(bsp, DownSampler);
RACK_PLUGIN_MODEL_DECLARE(bsp, Legato);
RACK_PLUGIN_MODEL_DECLARE(bsp, Obxd_VCF);
RACK_PLUGIN_MODEL_DECLARE(bsp, Rescaler);
RACK_PLUGIN_MODEL_DECLARE(bsp, RMS);
RACK_PLUGIN_MODEL_DECLARE(bsp, Scanner);
RACK_PLUGIN_MODEL_DECLARE(bsp, Sway);
RACK_PLUGIN_MODEL_DECLARE(bsp, TunedDelayLine);

RACK_PLUGIN_INIT(bsp) {
   RACK_PLUGIN_INIT_ID();
   RACK_PLUGIN_INIT_VERSION("0.6.1");
   RACK_PLUGIN_INIT_WEBSITE("https://github.com/bsp2/VeeSeeVSTRack/tree/v0.6/plugins/community/repos/bsp");

   RACK_PLUGIN_MODEL_ADD(bsp, AttenuMixer);
   RACK_PLUGIN_MODEL_ADD(bsp, Bias);
   RACK_PLUGIN_MODEL_ADD(bsp, DownSampler);
   RACK_PLUGIN_MODEL_ADD(bsp, Legato);
   RACK_PLUGIN_MODEL_ADD(bsp, Obxd_VCF);
   RACK_PLUGIN_MODEL_ADD(bsp, Rescaler);
   RACK_PLUGIN_MODEL_ADD(bsp, RMS);
   RACK_PLUGIN_MODEL_ADD(bsp, Scanner);
   RACK_PLUGIN_MODEL_ADD(bsp, Sway);
   RACK_PLUGIN_MODEL_ADD(bsp, TunedDelayLine);
}
