#include "Gratrix.hpp"

RACK_PLUGIN_MODEL_DECLARE(Gratrix, VCO_F1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, VCO_F2);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, VCF_F1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, VCA_F1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, ADSR_F1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Chord_G1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Octave_G1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Fade_G1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Fade_G2);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Binary_G1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Seq_G1);
// RACK_PLUGIN_MODEL_DECLARE(Gratrix, Seq_G2);  // assertion failed
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Keys_G1);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, VU_G1);
// RACK_PLUGIN_MODEL_DECLARE(Gratrix, Scope_G1); // assertion failed
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Blank_03);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Blank_06);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Blank_09);
RACK_PLUGIN_MODEL_DECLARE(Gratrix, Blank_12);

RACK_PLUGIN_INIT(Gratrix) {
   RACK_PLUGIN_INIT_ID();

   RACK_PLUGIN_MODEL_ADD(Gratrix, VCO_F1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, VCO_F2);
   RACK_PLUGIN_MODEL_ADD(Gratrix, VCF_F1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, VCA_F1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, ADSR_F1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Chord_G1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Octave_G1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Fade_G1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Fade_G2);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Binary_G1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Seq_G1);
   // RACK_PLUGIN_MODEL_ADD(Gratrix, Seq_G2); // assertion failed
   RACK_PLUGIN_MODEL_ADD(Gratrix, Keys_G1);
   RACK_PLUGIN_MODEL_ADD(Gratrix, VU_G1);
   // RACK_PLUGIN_MODEL_ADD(Gratrix, Scope_G1); // assertion failed
   RACK_PLUGIN_MODEL_ADD(Gratrix, Blank_03);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Blank_06);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Blank_09);
   RACK_PLUGIN_MODEL_ADD(Gratrix, Blank_12);
}
