SLUG=AudibleInstruments

include ../../../build_plugin_pre_msvc.mk

EXTRAFLAGS+= -Ieurorack/ -DTEST -Ieurorack/stmlib/third_party/STM -Ieurorack/stmlib/third_party/STM/STM32F0xx_StdPeriph_Driver/inc/ -Ieurorack/stmlib/third_party/STM/STM32F10x_StdPeriph_Driver/inc/ -Ieurorack/stmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc/ -Ieurorack/stmlib/third_party/STM/CMSIS/CM3_f37x/

include make.objects

include ../../../build_plugin_post_msvc.mk
