#
# Makefile for speex lib + GCC
# 
#

include ../yac/install_linux.mk

TARGET_BASENAME=libspeexdsp

EXTRAFLAGS= -D_GLFW_USE_CONFIG_H -DHAVE_CONFIG_H -Iinclude -I./

EXTRALIBS= 

PLAF_OBJ= 

include make.objects

ifeq ($(BUILD_64),y)
LIB_INSTALL_PREFIX=../lib/linux_gcc/x64/
else
LIB_INSTALL_PREFIX=../lib/linux_gcc/x86/
endif

include ../yac/staticlib_linux.mk
