SLUG=EH_modules

include ../../../build_shared_plugin_pre_msvc.mk

include make.objects

ALL_OBJ= $(COMMON_OBJ) $(WIN32_OBJ)

define BIN_POST_FXN
	cp -f $(SLUG).dll ../../../../vst2_bin/plugins/$(SLUG)/plugin.dll.fx
	cp -f $(SLUG).dll ../../../../vst2_bin/plugins/$(SLUG)/plugin.dll.instr
endef

include ../../../build_shared_plugin_post_msvc.mk
