SLUG=EH_modules

include ../../../build_shared_plugin_pre_linux.mk

include make.objects

ALL_OBJ= $(COMMON_OBJ)

define BIN_POST_FXN
	cp -f $(SLUG).so ../../../../vst2_bin/plugins/$(SLUG)/plugin.so.fx
	cp -f $(SLUG).so ../../../../vst2_bin/plugins/$(SLUG)/plugin.so.instr
endef

include ../../../build_shared_plugin_post_linux.mk
