#
# Makefile for jansson lib + Microsoft Visual C++ 2003 / 2005 / 2008 ToolKit
# 
#

include ../yac/install_msvc.mk

TARGET_BASENAME=jansson

EXTRAFLAGS= -I./ -Isrc/ -DHAVE_STDINT_H

EXTRALIBS=

PLAF_OBJ= 

include make.objects

include ../yac/staticlib_msvc.mk
