#
# Makefile for jansson lib + GCC
# 
#

include ../yac/install_linux.mk

TARGET_BASENAME=jansson

EXTRAFLAGS= -I./ -Isrc/ -DHAVE_STDINT_H

EXTRALIBS=

PLAF_OBJ= 

include make.objects

include ../yac/staticlib_linux.mk
