#include "Bark.hpp"

RACK_PLUGIN_MODEL_DECLARE(Bark, TrimLFO);
RACK_PLUGIN_MODEL_DECLARE(Bark, TrimLFObpm);
RACK_PLUGIN_MODEL_DECLARE(Bark, QuadLogic);
RACK_PLUGIN_MODEL_DECLARE(Bark, Panel6);
RACK_PLUGIN_MODEL_DECLARE(Bark, OneBand);

RACK_PLUGIN_INIT(Bark) {
   RACK_PLUGIN_INIT_ID();
   RACK_PLUGIN_INIT_VERSION("0.6.5");
   RACK_PLUGIN_INIT_WEBSITE("https://github.com/Coirt/Bark");

	RACK_PLUGIN_MODEL_ADD(Bark, TrimLFO);
	RACK_PLUGIN_MODEL_ADD(Bark, TrimLFObpm);
	RACK_PLUGIN_MODEL_ADD(Bark, QuadLogic);
	RACK_PLUGIN_MODEL_ADD(Bark, Panel6);
	RACK_PLUGIN_MODEL_ADD(Bark, OneBand);
}
