#include "Bidoo.hpp"

RACK_PLUGIN_MODEL_DECLARE(Bidoo, DTROY);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, BORDL);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, MU);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, TOCANTE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, CHUTE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, LATE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, LOURDE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, ACNE);
// RACK_PLUGIN_MODEL_DECLARE(Bidoo, OUAIVE); // GPL
// RACK_PLUGIN_MODEL_DECLARE(Bidoo, CANARD); // GPL
RACK_PLUGIN_MODEL_DECLARE(Bidoo, DUKE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, MOIRE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, FORK);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, TIARE);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, CLACOS);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, ANTN);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, LIMBO);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, PERCO);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, BAR);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, ZINC);
// RACK_PLUGIN_MODEL_DECLARE(Bidoo, DFUZE); // clashes with AS modules
//RACK_PLUGIN_MODEL_DECLARE(Bidoo, HORUS);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, VOID);
RACK_PLUGIN_MODEL_DECLARE(Bidoo, SIGMA);

RACK_PLUGIN_INIT(Bidoo) {
   RACK_PLUGIN_INIT_ID();

	RACK_PLUGIN_MODEL_ADD(Bidoo, DTROY);
	RACK_PLUGIN_MODEL_ADD(Bidoo, BORDL);
	RACK_PLUGIN_MODEL_ADD(Bidoo, MU);
	RACK_PLUGIN_MODEL_ADD(Bidoo, TOCANTE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, CHUTE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, LATE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, LOURDE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, ACNE);
	// RACK_PLUGIN_MODEL_ADD(Bidoo, OUAIVE); // GPL
	// RACK_PLUGIN_MODEL_ADD(Bidoo, CANARD); // GPL
	RACK_PLUGIN_MODEL_ADD(Bidoo, DUKE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, MOIRE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, FORK);
	RACK_PLUGIN_MODEL_ADD(Bidoo, TIARE);
	RACK_PLUGIN_MODEL_ADD(Bidoo, CLACOS);
	RACK_PLUGIN_MODEL_ADD(Bidoo, ANTN);
	RACK_PLUGIN_MODEL_ADD(Bidoo, LIMBO);
	RACK_PLUGIN_MODEL_ADD(Bidoo, PERCO);
	RACK_PLUGIN_MODEL_ADD(Bidoo, BAR);
	RACK_PLUGIN_MODEL_ADD(Bidoo, ZINC);
	// RACK_PLUGIN_MODEL_ADD(Bidoo, DFUZE); // clashes with AS modules
	//RACK_PLUGIN_MODEL_ADD(Bidoo, HORUS);
	RACK_PLUGIN_MODEL_ADD(Bidoo, VOID);
	RACK_PLUGIN_MODEL_ADD(Bidoo, SIGMA);
}
