SLUG=Autodafe

#include ../../../build_shared_plugin_pre.mk
include ../../../build_plugin_pre.mk

CPPFLAGS+= -Idep/ -Idep/stk/include/

include make.objects

define BIN_POST_FXN
	cp -f $(SLUG).dll ../../../../vst2_bin/plugins/$(SLUG)/plugin.dll
endef

#include ../../../build_shared_plugin_post.mk
include ../../../build_plugin_post.mk
