#include "pvc.hpp"

RACK_PLUGIN_MODEL_DECLARE(PvC, Heads);
RACK_PLUGIN_MODEL_DECLARE(PvC, Tails);
RACK_PLUGIN_MODEL_DECLARE(PvC, BangDaButton);
RACK_PLUGIN_MODEL_DECLARE(PvC, Compair);
RACK_PLUGIN_MODEL_DECLARE(PvC, CoSuOf);
RACK_PLUGIN_MODEL_DECLARE(PvC, FlipOLogic);
RACK_PLUGIN_MODEL_DECLARE(PvC, Geighths);
RACK_PLUGIN_MODEL_DECLARE(PvC, ShutIt);
RACK_PLUGIN_MODEL_DECLARE(PvC, SlimSeq);
RACK_PLUGIN_MODEL_DECLARE(PvC, SumIt);
RACK_PLUGIN_MODEL_DECLARE(PvC, TaHaSaHaN);
RACK_PLUGIN_MODEL_DECLARE(PvC, Vamps);
RACK_PLUGIN_MODEL_DECLARE(PvC, Vubar);
RACK_PLUGIN_MODEL_DECLARE(PvC, PvCBlank);
RACK_PLUGIN_MODEL_DECLARE(PvC, PlainVoidCanvas);

RACK_PLUGIN_INIT(PvC) {
   RACK_PLUGIN_INIT_ID();

   RACK_PLUGIN_INIT_WEBSITE("https://github.com/phdsg/PvC");

	RACK_PLUGIN_MODEL_ADD(PvC, Heads);
	RACK_PLUGIN_MODEL_ADD(PvC, Tails);
	RACK_PLUGIN_MODEL_ADD(PvC, BangDaButton);
	RACK_PLUGIN_MODEL_ADD(PvC, Compair);
	RACK_PLUGIN_MODEL_ADD(PvC, CoSuOf);
	RACK_PLUGIN_MODEL_ADD(PvC, FlipOLogic);
	RACK_PLUGIN_MODEL_ADD(PvC, Geighths);
	RACK_PLUGIN_MODEL_ADD(PvC, ShutIt);
	RACK_PLUGIN_MODEL_ADD(PvC, SlimSeq);
	RACK_PLUGIN_MODEL_ADD(PvC, SumIt);
	RACK_PLUGIN_MODEL_ADD(PvC, TaHaSaHaN);
	RACK_PLUGIN_MODEL_ADD(PvC, Vamps);
	RACK_PLUGIN_MODEL_ADD(PvC, Vubar);
	RACK_PLUGIN_MODEL_ADD(PvC, PvCBlank);
	RACK_PLUGIN_MODEL_ADD(PvC, PlainVoidCanvas);
}
