module DHE
  MM_PER_INCH = 25.4
  PX_PER_INCH = 75.0
  PX_PER_MM = PX_PER_INCH / MM_PER_INCH
  MM_PER_HP = 5.08

  PANEL_HEIGHT = 128.5
  PANEL_LABEL_INSET = 9.0

  STROKE_WIDTH = 0.35
  STROKE_INSET = STROKE_WIDTH / 2.0
  PADDING = 1.0
end
